### PR TITLE
ss-14: Add Extension For Auto-generation Id Keys In DB

### PR DESCRIPTION
**Pull request by vasylpopovych**

### CODE REVIEW

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]
we don't change migration, we should create new on

**Review by nikita-remeslov — COMMENTED** [review]
https://knexjs.org/guide/schema-builder.html#alter

**Review by VItaliy-Kalenichenko — CHANGES_REQUESTED** [review]
.

**Review by VItaliy-Kalenichenko — APPROVED** [review]

**Review by VItaliy-Kalenichenko — CHANGES_REQUESTED** [review]
image

**Review by VItaliy-Kalenichenko — APPROVED** [review]

**Pull request merged**
